# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from api.environments_api import EnvironmentsApi  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = api.environments_api.EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_environment(self):
        """Test case for create_environment

        create environment on account  # noqa: E501
        """
        pass

    def test_delete_environment_by_id(self):
        """Test case for delete_environment_by_id

        delete environment on account  # noqa: E501
        """
        pass

    def test_get_environment_by_id(self):
        """Test case for get_environment_by_id

        get specific environment on account  # noqa: E501
        """
        pass

    def test_list_environments_for_account(self):
        """Test case for list_environments_for_account

        search or list environments on an account  # noqa: E501
        """
        pass

    def test_update_environment_by_id(self):
        """Test case for update_environment_by_id

        update environment on account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
