# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from models.run_response import RunResponse  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestRunResponse(unittest.TestCase):
    """RunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunResponse(self):
        """Test RunResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dbt_cloud_client.models.run_response.RunResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
