# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from api.credentials_api import CredentialsApi  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self):
        self.api = api.credentials_api.CredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_credentials(self):
        """Test case for create_credentials

        create credentials on account  # noqa: E501
        """
        pass

    def test_list_credentials_for_account(self):
        """Test case for list_credentials_for_account

        search or list credentials on an account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
