# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from models.one_of_connection_response_data import OneOfConnectionResponseData  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestOneOfConnectionResponseData(unittest.TestCase):
    """OneOfConnectionResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfConnectionResponseData(self):
        """Test OneOfConnectionResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dbt_cloud_client.models.one_of_connection_response_data.OneOfConnectionResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
