# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from models.body4 import Body4  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestBody4(unittest.TestCase):
    """Body4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody4(self):
        """Test Body4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dbt_cloud_client.models.body4.Body4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
