# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from api.accounts_api import AccountsApi  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_by_id(self):
        """Test case for get_account_by_id

        get account by id  # noqa: E501
        """
        pass

    def test_list_accounts(self):
        """Test case for list_accounts

        search or list accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
