# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dbt_cloud_client
from api.connections_api import ConnectionsApi  # noqa: E501
from dbt_cloud_client.rest import ApiException


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self):
        self.api = api.connections_api.ConnectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_connection(self):
        """Test case for create_connection

        create connection on account  # noqa: E501
        """
        pass

    def test_delete_connection_by_id(self):
        """Test case for delete_connection_by_id

        delete connection on account  # noqa: E501
        """
        pass

    def test_get_connection_by_id(self):
        """Test case for get_connection_by_id

        get specific connection on account  # noqa: E501
        """
        pass

    def test_list_connections_for_account(self):
        """Test case for list_connections_for_account

        search or list connections on an account  # noqa: E501
        """
        pass

    def test_update_connection_by_id(self):
        """Test case for update_connection_by_id

        update connection on account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
