# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cause': 'str',
        'git_sha': 'str',
        'git_branch': 'str'
    }

    attribute_map = {
        'cause': 'cause',
        'git_sha': 'git_sha',
        'git_branch': 'git_branch'
    }

    def __init__(self, cause=None, git_sha=None, git_branch=None):  # noqa: E501
        """Body3 - a model defined in Swagger"""  # noqa: E501
        self._cause = None
        self._git_sha = None
        self._git_branch = None
        self.discriminator = None
        if cause is not None:
            self.cause = cause
        if git_sha is not None:
            self.git_sha = git_sha
        if git_branch is not None:
            self.git_branch = git_branch

    @property
    def cause(self):
        """Gets the cause of this Body3.  # noqa: E501


        :return: The cause of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this Body3.


        :param cause: The cause of this Body3.  # noqa: E501
        :type: str
        """

        self._cause = cause

    @property
    def git_sha(self):
        """Gets the git_sha of this Body3.  # noqa: E501


        :return: The git_sha of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._git_sha

    @git_sha.setter
    def git_sha(self, git_sha):
        """Sets the git_sha of this Body3.


        :param git_sha: The git_sha of this Body3.  # noqa: E501
        :type: str
        """

        self._git_sha = git_sha

    @property
    def git_branch(self):
        """Gets the git_branch of this Body3.  # noqa: E501


        :return: The git_branch of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._git_branch

    @git_branch.setter
    def git_branch(self, git_branch):
        """Sets the git_branch of this Body3.


        :param git_branch: The git_branch of this Body3.  # noqa: E501
        :type: str
        """

        self._git_branch = git_branch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
