# coding: utf-8

"""
    dbt Cloud API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0a1
    Contact: support@getdbt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class JobTriggers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'github_webhook': 'bool',
        'schedule': 'bool'
    }

    attribute_map = {
        'github_webhook': 'github_webhook',
        'schedule': 'schedule'
    }

    def __init__(self, github_webhook=None, schedule=None):  # noqa: E501
        """JobTriggers - a model defined in Swagger"""  # noqa: E501
        self._github_webhook = None
        self._schedule = None
        self.discriminator = None
        if github_webhook is not None:
            self.github_webhook = github_webhook
        if schedule is not None:
            self.schedule = schedule

    @property
    def github_webhook(self):
        """Gets the github_webhook of this JobTriggers.  # noqa: E501


        :return: The github_webhook of this JobTriggers.  # noqa: E501
        :rtype: bool
        """
        return self._github_webhook

    @github_webhook.setter
    def github_webhook(self, github_webhook):
        """Sets the github_webhook of this JobTriggers.


        :param github_webhook: The github_webhook of this JobTriggers.  # noqa: E501
        :type: bool
        """

        self._github_webhook = github_webhook

    @property
    def schedule(self):
        """Gets the schedule of this JobTriggers.  # noqa: E501


        :return: The schedule of this JobTriggers.  # noqa: E501
        :rtype: bool
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this JobTriggers.


        :param schedule: The schedule of this JobTriggers.  # noqa: E501
        :type: bool
        """

        self._schedule = schedule

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobTriggers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobTriggers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
